receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  # Local Jaeger exporter
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

  # New Relic exporter
  otlp/newrelic:
    endpoint: "https://otlp.nr-data.net:4317" # Use https://otlp.eu01.nr-data.net:4317 for EU accounts
    headers:
      api-key: "${NEW_RELIC_LICENSE_KEY}"

  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger, otlp/newrelic, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/newrelic, logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/newrelic, logging]
