receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317   
      http:
        cors:
          allowed_origins:
          - http://*
          - https://*
        endpoint: 0.0.0.0:4318   

processors:
  batch:
    send_batch_max_size: 200
    send_batch_size: 200
    timeout: 5s

  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 20

  resourcedetection:
    detectors: [gcp]
    timeout: 10s

exporters:
  otlp/newrelic:
    endpoint: otlp.nr-data.net:4317  
    headers:
      api-key: "${env:NEW_RELIC_LICENSE_KEY}"  
    compression: gzip

extensions:
  health_check:
    endpoint: 0.0.0.0:13133   

service:
  extensions:
  - health_check
  pipelines:
    logs:
      receivers:
      - otlp
      processors:
      - resourcedetection
      - memory_limiter
      - batch
      exporters:
      - otlp/newrelic

    metrics:
      receivers:
      - otlp
      processors:
      - resourcedetection
      - memory_limiter
      - batch
      exporters:
      - otlp/newrelic

    traces:
      receivers:
      - otlp
      processors:
      - resourcedetection
      - memory_limiter
      - batch
      exporters:
      - otlp/newrelic

  telemetry:
    metrics:
      readers:
        - periodic:
            exporter:
              otlp:
                protocol: grpc
                endpoint: localhost:4317   
                insecure: true